#!/bin/bash

# This is based on David Mills work you can find at https://github.com/g7uvw/rPI-multiDS18x20
# You can get the latest version of this file from https://github.com/maronai/cubieboard

rrdtool create koszeg_temp-10years-3sensors.rrd \
	--step 300 \
	DS:living_room_temp:GAUGE:600:-30:50 \
	DS:outside_temp:GAUGE:1200:-30:50 \
	DS:dining_room_temp:GAUGE:1200:-30:50 \
	RRA:AVERAGE:0.5:1:1051200 \
	RRA:AVERAGE:0.5:1:12 \
	RRA:AVERAGE:0.5:1:288 \
	RRA:AVERAGE:0.5:6:336 \
	RRA:AVERAGE:0.5:6:1440 \
	RRA:AVERAGE:0.5:288:365 \

#taking measurement every 5 min (60s*5=300)
#Data Sources for 3 room measurements, having GAUGE type,
#waiting 600 second until making the measurement unknown if not received
#ranging from -30 to 50
#store average, with 0.5 xFilesFactor, 1 data point is consolidated, 10 years data is stored
#hourly store: 5min*12=60
#daily store:  12*24=288
#weekly store, taking 6*5min=30min average into account: 1week = 168h = 336 half_an_hour
#monthly store, 30days*48 half_an_hour 
#yearly store, taking daily averages
